name: wifi
description: Flutter plugin providing WiFi.
author: Lewis <once10301@gmail.com>
homepage: https://github.com/once10301/wifi
version: 0.1.5

environment:
  sdk: ">=3.1.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.wifi
    pluginClass: WifiPlugin

